<template>
  <div class="p-boxs" v-if="list.length">
    <div class="boxs fade-in-top">
      <div class="boxs-item" v-for="item in list" :key="item._id" @click="jump(item._id)">
        <div class="boxs-img">
          <img :src="item.content | getImg" alt="" />
        </div>
        <div class="boxs-content">
          <div class="tag">{{ item.tagId.tag }}</div>
          <div class="boxs-sec2">
            <div class="title">{{ item.title }}</div>
            <div class="bottom">
              <div>{{ item.date | getDate }}</div>
              <div class="circle">•</div>
              <div class="watch">{{ item.watch }}次围观</div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- 分页 -->
    <div class="pagination">
      <div class="left circle" @click="pageChange(-1)" v-if="pages.page != 1">
        <i class="el-icon-back"></i>
      </div>
      <span>Page</span>
      <span>{{ pages.page }}</span>
      <span>of</span>
      <span>{{ pages.count }}</span>
      <div class="right circle" @click="pageChange(1)" v-if="pages.page != pages.count">
        <i class="el-icon-right"></i>
      </div>
    </div>
  </div>
  <div v-else class="err jello-horizontal">没有数据哦</div>
</template>

<script>
import { getImg, getDate } from '@/assets/js/filter.js';
export default {
  props: {
    list: {
      type: Array
    },
    pages: {
      type: Object
    }
  },
  methods: {
    jump(id) {
      this.$router.push({
        path: 'detail',
        query: {
          id
        }
      });
    },
    pageChange(flag) {
      this.$emit('pageChange', flag);
    }
  },
  filters: {
    getImg,
    getDate
  }
};
</script>

<style lang="scss" scoped>
.boxs {
  width: 100%;
  @include flex;
  justify-content: flex-start;
  flex-wrap: wrap;
  .boxs-item {
    width: calc(33% - 40px);
    margin: 0 20px;
    background: $baseColor;
    margin-bottom: 50px;
    cursor: pointer;
    transition: all 0.25s cubic-bezier(0.02, 0.01, 0.47, 1);
    color: $baseColor2;
    &:hover {
      transform: translateY(-5px);
      .boxs-content {
        box-shadow: $article-shadow-hover;
      }
    }
    .boxs-img {
      height: 200px;
      img {
        width: 100%;
        height: 100%;
        border-radius: 5px 5px 0 0;
        object-fit: cover;
      }
    }
    .boxs-content {
      height: 200px;
      border-radius: 0 0 5px 5px;
      box-shadow: $article-shadow-normal;
      transition: all 0.25s cubic-bezier(0.02, 0.01, 0.47, 1);
      box-sizing: border-box;
      padding: 30px 20px;
      .tag {
        font-weight: bold;
      }
      .boxs-sec2 {
        height: calc(100% - 20px);
        @include flex(column);
        justify-content: space-between;
        align-items: flex-start;
        .title {
          font-size: 20px;
          height: 40px;
          line-height: 40px;
          @include ellipsis(2);
          font-weight: bold;
        }
        .bottom {
          font-size: 14px;
          @include flex;
          .circle {
            padding: 0 10px;
          }
        }
      }
    }
  }
}
.fade-in-top {
  -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-27 12:19:1
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
@keyframes fade-in-top {
  0% {
    -webkit-transform: translateY(-50px);
    transform: translateY(-50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    opacity: 1;
  }
}
/*  */
.p-boxs {
  @include flex(column);
}
.pagination {
  margin: 0 auto;
  @include flex;
  justify-content: flex-start;
  span {
    margin-right: 5px;
  }
  .left {
    margin-left: 0;
    margin-right: 15px;
  }
  .circle {
    width: 50px;
    height: 50px;
    background-color: #fff;
    border-radius: 50%;
    @include flex;
    margin-left: 10px;
    font-size: 22px;
    cursor: pointer;
    transition: all 0.3s;
    box-shadow: 0 10px 10px -10px rgba(0, 0, 0, 0.3);
    &:hover {
      box-shadow: 0 10px 10px -10px rgba(0, 0, 0, 0.5);
    }
  }
}
.err {
  text-align: center;
  font-size: 22px;
}
.jello-horizontal {
  -webkit-animation: jello-horizontal 0.9s both;
  animation: jello-horizontal 0.9s both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-4-29 21:28:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
    transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
    transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
    transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
    transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
    transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
    transform: scale3d(1, 1, 1);
  }
}
/* h5 */
@media screen and (max-width: 1000px) {
  .boxs {
    .boxs-item {
      width: calc(50% - 40px) !important;
    }
  }
}
@media screen and (max-width: 768px) {
  .boxs {
    .boxs-item {
      width: calc(100% - 20px) !important;
      margin: 0 10px;
      margin-bottom: 30px;
    }
  }
}
</style>
